name: pipeline
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: step1
        run: actions/checkout@v2
      - name: my-step
        run: ci/build-app.sh